using Celeste.Mod.TheCelesteTracker_Mod.Database;
using CommonCode;
using Microsoft.Xna.Framework;
using MonoMod.ModInterop;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using static On.Celeste.Level;
using static On.Celeste.Player;
using static On.Celeste.SaveData;
using Db = Celeste.Mod.TheCelesteTracker_Mod.Database;
//Some useful events (self-documentation)
//On.Celeste.Player.Die -= Player_Die;
//On.Celeste.Level.TransitionRoutine -= Level_TransitionRoutine;
//On.Celeste.Level.RegisterAreaComplete -= Level_RegisterAreaComplete;
//On.Celeste.LevelExit.ctor -= LevelExit_ctor;
//Everest.Events.FileSelectSlot.OnCreateButtons -= OnFileSelectSlotCreateButtons;


#nullable enable
namespace Celeste.Mod.TheCelesteTracker_Mod
{


    public class TheCelesteTracker_ModModule : EverestModule
    {
        public static TheCelesteTracker_ModModule Instance { get; private set; } = null!;
        public override Type SettingsType => typeof(TheCelesteTracker_ModModuleSettings);
        public static TheCelesteTracker_ModModuleSettings Settings => (TheCelesteTracker_ModModuleSettings)Instance._Settings;

        public override Type SessionType => typeof(TheCelesteTracker_ModModuleSession);
        public static TheCelesteTracker_ModModuleSession ModSession => (TheCelesteTracker_ModModuleSession)Instance._Session;

        public override Type SaveDataType => typeof(TheCelesteTracker_ModModuleSaveData);
        public static TheCelesteTracker_ModModuleSaveData ModSaveData => (TheCelesteTracker_ModModuleSaveData)Instance._SaveData;


        public static ISimpleLogger l = new TheCelesteModTrackerLogger();


        public static CelesteTrackerDb DB = null!; //Will be immedidately instantiated in static constructor()

        static TheCelesteTracker_ModModule()
        {
            System.Diagnostics.Debugger.Break(); // forces VS to stop here
            // Assembly.Location can be empty in Everest - find the DLL by other means
            // e_sqlite3.dll is in the mod folder, not the game root - search for it
            string sqlitePath = Path.Join(Everest.PathGame, "Mods", "TheCelesteTracker", "e_sqlite3.dll");
            NativeLibrary.Load(sqlitePath);

#if DEBUG
            DB = new CelesteTrackerDb(Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "TheCelesteTracker_MOD_DB_TEST_AUTOGENERATED.db"), l);
#else
            DB = new CelesteTrackerDb(Path.Join(Everest.PathGame, "Saves", "TheCelesteTracker_DB.db"), l);
#endif
        }



        public TheCelesteTracker_ModModule()
        {
            Instance = this;
#if DEBUG
            Logger.SetLogLevel(nameof(TheCelesteTracker_ModModule), LogLevel.Verbose);
#else
            Logger.SetLogLevel(nameof(TheCelesteTracker_ModModule), LogLevel.Info);
#endif
        }

        public override void Load()
        {
            typeof(TheCelesteTracker_ModExports).ModInterop();

            On.Celeste.SaveData.StartSession += OnLevelSessionStart;
            On.Celeste.Strawberry.OnPlayer += OnStrawberryCollectionPlayer;

            On.Celeste.Player.DashBegin += Player_DashBegin;
            On.Celeste.Level.Begin += OnLevelBegin;
            On.Celeste.Level.NextLevel += OnNextRoom;
            On.Celeste.Level.End += OnLevelSessionEnd;

            Everest.Events.MainMenu.OnCreateButtons += OnMainMenuCreateButtons;

            //TrackerWebSocketServer.Start();
            // Force Windows to load e_sqlite3 from our mod's directory

            Logger.Log(LogLevel.Info, nameof(TheCelesteTracker_ModModule), "Module Loaded!");
        }

        public override void Unload()
        {
            On.Celeste.SaveData.StartSession -= OnLevelSessionStart;
            On.Celeste.Strawberry.OnPlayer += OnStrawberryCollectionPlayer;

            On.Celeste.Player.DashBegin -= Player_DashBegin;
            On.Celeste.Level.Begin -= OnLevelBegin;
            On.Celeste.Level.NextLevel -= OnNextRoom;
            On.Celeste.Level.End -= OnLevelSessionEnd;
            Everest.Events.MainMenu.OnCreateButtons -= OnMainMenuCreateButtons;


            //TrackerWebSocketServer.Stop();
        }

        private static async void OnStrawberryCollectionPlayer(On.Celeste.Strawberry.orig_OnPlayer orig, global::Celeste.Strawberry self, global::Celeste.Player player)
        {
            orig(self, player);
            if (self.Golden)
            {
                ModSession.CurrentSession?.IsGoldenBerryAttempt = true;
            }
            l.Log(new { Event = "OnStrawBerryCollection", isGoldenStrawBerry = self.Golden, berryInfo = self });
        }


        /// <summary>
        /// When playing for the first time a chapter, or "Save and quit" and then entering into save file again
        /// </summary>
        /// <param name="orig"></param>
        /// <param name="self"></param>
        /// <param name="session"></param>
        private static async void OnLevelSessionStart(orig_StartSession orig, global::Celeste.SaveData self, global::Celeste.Session session)
        {
            orig(self, session);

            global::Celeste.AreaData currentChapterData = AreaData.Get(session.Area);
            int totalBerries = currentChapterData.Mode.Sum(mode => mode.TotalStrawberries);

            ModSession.CurrentSession = await DB.GetCurrentSessionFullStats(
                self.Name,
                self.FileSlot,
                session.Area.LevelSet,
                session.Area.GetSID(),
                session.Area.Mode.ToStringId(),
                totalBerries
            );

            l.Log(new { Event = "OnLevelStart" });
        }

        /// <summary>
        /// When entering into main menu. Like a startup() method, but in-game
        /// </summary>
        /// <param name="menu"></param>
        /// <param name="buttons"></param>
        private void OnMainMenuCreateButtons(OuiMainMenu menu, List<MenuButton> buttons)
        {
            l.Log(new { Event = "OnMainMenuCreateButtons", msg = "Main Menu!!", });
        }

        /// <summary>
        /// When going to main manú and pressing "Save and quit"
        /// </summary>
        /// <param name="orig"></param>
        /// <param name="self"></param>
        private static void OnLevelSessionEnd(orig_End orig, global::Celeste.Level self)
        {
            orig(self);
            l.Log(new { Event = "Level_End" });
        }


        /// <summary>
        /// When going to next room only in same chapter (Moving across rooms)
        /// </summary>
        /// <param name="orig"></param>
        /// <param name="self"></param>
        /// <param name="at"></param>
        /// <param name="dir"></param>
        private static void OnNextRoom(orig_NextLevel orig, global::Celeste.Level self, Vector2 at, Vector2 dir)
        {
            orig(self, at, dir);
            l.Log(new { Event = "Level_NextLevel", RoomInfo = new { CurrentDeaths = self.Session.Deaths } });//Full total count of datasave
        }


        private static void Player_DashBegin(orig_DashBegin orig, global::Celeste.Player self)
        {
            orig(self);
            l.Log(new { Event = "Dash_Begin" });
        }


        private static void OnLevelBegin(On.Celeste.Level.orig_Begin orig, Level self)
        {
            orig(self);
            var ev = new
            {
                Type = "LevelBegin",
                AreaSid = self.Session.Area.GetSID(),
                ChapterName = Dialog.Clean(AreaData.Get(self.Session.Area).Name),
                RoomName = self.Session.Level,
                Mode = self.Session.Area.Mode.ToString()
            };
            l.Log(ev);
        }
    }
}
//private void OnFileSelectSlotCreateButtons(List<OuiFileSelectSlot.Button> buttons, OuiFileSelectSlot slot, EverestModuleSaveData modSaveData, bool fileExists)
//{
//    // 'slot' es el objeto visual de la ranura (ranura 0, 1, 2...)
//    // 'slot.SaveData' contiene la información de vainilla (muertes, tiempo, etc.)
//    Loggy.Log(new
//    {
//        Event = "OnFileSelectSlot",
//        OuiFileSelectSlotListInfoRaw = buttons.Select((button) =>
//        {
//            return new
//            {
//                label = button.Label,
//                scale = button.Scale,
//            };
//        })
//    });

//    if (fileExists && slot.SaveData != null)
//    {
//        int index = slot.buttonIndex;
//        long muertes = slot.SaveData.TotalDeaths;
//        string nombre = slot.SaveData.Name;

//        Logger.Log(LogLevel.Info, "MiTracker", $"Visualizando Slot {index} ({nombre}): {muertes} muertes totales.");
//    }
//}
