using Celeste.Mod.TheCelesteTracker_Mod.Database;
using CommonCode;
using Microsoft.Xna.Framework;
using MonoMod.ModInterop;
using System;
using System.IO;
using System.Runtime.InteropServices;
using static On.Celeste.Level;
using static On.Celeste.Player;
using static On.Celeste.SaveData;
//Some useful events (self-documentation)
//On.Celeste.Player.Die -= Player_Die;
//On.Celeste.Level.TransitionRoutine -= Level_TransitionRoutine;
//On.Celeste.Level.RegisterAreaComplete -= Level_RegisterAreaComplete;
//On.Celeste.LevelExit.ctor -= LevelExit_ctor;
//Everest.Events.FileSelectSlot.OnCreateButtons -= OnFileSelectSlotCreateButtons;
//On.Celeste.Level.Begin += OnLevelBegin;
//Everest.Events.MainMenu.OnCreateButtons += OnMainMenuCreateButtons;



#nullable enable
namespace Celeste.Mod.TheCelesteTracker_Mod
{

    /// <summary>
    /// Not a DATABASE table, just a helpful DTO for internal mod use.
    /// </summary>
    public record class DbSessionContext
    {
        public required GameSession Session { get; set; }
        public required SaveData SaveData { get; set; }
        public required Campaign Campaign { get; set; }
        public required Chapter Chapter { get; set; }
    }


    public class TheCelesteTracker_ModModule : EverestModule
    {
        public static TheCelesteTracker_ModModule Instance { get; private set; } = null!;
        public override Type SettingsType => typeof(TheCelesteTracker_ModModuleSettings);
        public static TheCelesteTracker_ModModuleSettings Settings => (TheCelesteTracker_ModModuleSettings)Instance._Settings;

        public override Type SessionType => typeof(TheCelesteTracker_ModModuleSession);
        public static TheCelesteTracker_ModModuleSession ModSession => (TheCelesteTracker_ModModuleSession)Instance._Session;

        public override Type SaveDataType => typeof(TheCelesteTracker_ModModuleSaveData);
        public static TheCelesteTracker_ModModuleSaveData ModSaveData => (TheCelesteTracker_ModModuleSaveData)Instance._SaveData;


        public static ISimpleLogger l = new TheCelesteModTrackerLogger();


        public static CelesteTrackerDb DB = null!; //Will be immedidately instantiated in static constructor()

        static TheCelesteTracker_ModModule()
        {
            string sqlitePath = Path.Join(Everest.PathGame, "Mods", "TheCelesteTracker", "e_sqlite3.dll");
            NativeLibrary.Load(sqlitePath);
#if DEBUG
            DB = new CelesteTrackerDb(Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "TheCelesteTracker_MOD_DB_TEST_AUTOGENERATED.db"), l);
#else
            DB = new CelesteTrackerDb(Path.Join(Everest.PathGame, "Saves", "TheCelesteTracker_DB.db"), l);
#endif
        }


        public TheCelesteTracker_ModModule()
        {
            Instance = this;
#if DEBUG
            Logger.SetLogLevel(nameof(TheCelesteTracker_ModModule), LogLevel.Verbose);
#else
            Logger.SetLogLevel(nameof(TheCelesteTracker_ModModule), LogLevel.Info);
#endif
        }

        public override void Load()
        {
            typeof(TheCelesteTracker_ModExports).ModInterop();

            On.Celeste.SaveData.StartSession += OnLevelSessionStart;
            On.Celeste.Strawberry.OnPlayer += OnStrawberryCollectionPlayer;

            On.Celeste.Player.DashBegin += Player_DashBegin;
            On.Celeste.Level.NextLevel += OnNextRoom;
            On.Celeste.Level.LoadLevel += OnLoadRoomLevel;
            On.Celeste.Level.End += OnLevelSessionEnd;


            Logger.Log(LogLevel.Info, nameof(TheCelesteTracker_ModModule), "Module Loaded!");
            //TrackerWebSocketServer.Start();
        }

        public static async void OnLoadRoomLevel(orig_LoadLevel orig, global::Celeste.Level self, global::Celeste.Player.IntroTypes playerIntro, bool isFromLoader)
        {
            orig(self, playerIntro, isFromLoader);

            //if (ModSession.LastRoomLevel is null)
            //{
            //    //This means we're in our first room, we're starting the chapter
            //}


            ModSession.LastRoomLevel = self;
            l.Log(new { Event = "OnLoadRoom" });
        }

        public override void Unload()
        {
            On.Celeste.SaveData.StartSession -= OnLevelSessionStart;
            On.Celeste.Strawberry.OnPlayer += OnStrawberryCollectionPlayer;

            On.Celeste.Player.DashBegin -= Player_DashBegin;
            On.Celeste.Level.NextLevel -= OnNextRoom;
            On.Celeste.Level.End -= OnLevelSessionEnd;
            On.Celeste.Level.LoadLevel -= OnLoadRoomLevel;

            //TrackerWebSocketServer.Stop();
        }

        private static async void OnStrawberryCollectionPlayer(On.Celeste.Strawberry.orig_OnPlayer orig, global::Celeste.Strawberry self, global::Celeste.Player player)
        {
            orig(self, player);
            if (self.Golden)
            {
                ModSession.CurrentSession?.IsGoldenBerryAttempt = true;
            }
            l.Log(new { Event = "OnStrawBerryCollection", isGoldenStrawBerry = self.Golden, berryInfo = self });
        }


        /// <summary>
        /// When playing for the first time a chapter, or "Save and quit" and then entering into save file again
        /// </summary>
        private static async void OnLevelSessionStart(orig_StartSession orig, global::Celeste.SaveData self, global::Celeste.Session session)
        {
            orig(self, session);

            DbSessionContext context = await DB.EnsureSessionInDB(session);
            ModSession.CurrentSession = context.Session;
            ModSession.CurrentSession.AddRoomStat

            l.Log(new { Event = "OnLevelStart" });
        }


        /// <summary>
        /// When going to main manú and pressing "Save and quit"
        /// </summary>
        private static async void OnLevelSessionEnd(orig_End orig, global::Celeste.Level self)
        {
            orig(self);
            if (ModSession.CurrentSession is not null)
            {
                await DB.InsertGameSession(ModSession.CurrentSession);
                l.Log(new { Event = "Level_End:CurrentSessionDetected!, storing session info in DB", SessionInfo = ModSession.CurrentSession });
                ModSession.CurrentSession = null;
            }
            else
            {

                l.Log(new { Event = "Level_End:CurrentSeasonNotDetected!, storing session info in DB", SessionInfo = ModSession.CurrentSession });
            }
        }


        /// <summary>
        /// When going to next room only in same chapter (Moving across rooms)
        /// </summary>
        private static void OnNextRoom(orig_NextLevel orig, global::Celeste.Level self, Vector2 at, Vector2 dir)
        {
            orig(self, at, dir);
            l.Log(new { Event = "Level_NextLevel", RoomInfo = new { CurrentDeaths = self.Session.Deaths } });//Full total count of datasave for some reason
        }

        private static void Player_DashBegin(orig_DashBegin orig, global::Celeste.Player self)
        {
            orig(self);
            l.Log(new { Event = "Dash_Begin" });
        }
    }
}
//private void OnFileSelectSlotCreateButtons(List<OuiFileSelectSlot.Button> buttons, OuiFileSelectSlot slot, EverestModuleSaveData modSaveData, bool fileExists)
//{
//    // 'slot' es el objeto visual de la ranura (ranura 0, 1, 2...)
//    // 'slot.SaveData' contiene la información de vainilla (muertes, tiempo, etc.)
//    Loggy.Log(new
//    {
//        Event = "OnFileSelectSlot",
//        OuiFileSelectSlotListInfoRaw = buttons.Select((button) =>
//        {
//            return new
//            {
//                label = button.Label,
//                scale = button.Scale,
//            };
//        })
//    });

//    if (fileExists && slot.SaveData != null)
//    {
//        int index = slot.buttonIndex;
//        long muertes = slot.SaveData.TotalDeaths;
//        string nombre = slot.SaveData.Name;

//        Logger.Log(LogLevel.Info, "MiTracker", $"Visualizando Slot {index} ({nombre}): {muertes} muertes totales.");
//    }
//}



//private static void OnLevelBegin(On.Celeste.Level.orig_Begin orig, Level self)
//{
//    orig(self);
//    var ev = new
//    {
//        Type = "LevelBegin",
//        AreaSid = self.Session.Area.GetSID(),
//        ChapterName = Dialog.Clean(AreaData.Get(self.Session.Area).Name),
//        RoomName = self.Session.Level,
//        Mode = self.Session.Area.Mode.ToString()
//    };
//    l.Log(ev);
//}



//ModSession.CurrentSession.RoomStats.Add(new GameSessionChapterRoomStats
//{
//    RoomName = firstRoom.Name,
//    Deaths = ModSession.CurrentRoomDeaths = 0

//});

/// <summary>
/// Not a DATABASE table, just a helpful DTO for internal mod use.
/// </summary>
//public record class LocalChapterRoomInfo
//{
//    public required int Deaths;
//    public required int Dashes;
//    public required int StrawberriesAchieved;
//    public required int HeartsAchieved;
//}


