using Celeste.Mod.TheCelesteTracker_Mod.Database;
using Celeste.Mod.TheCelesteTracker_Mod.Source.services;
using CommonCode;
using Microsoft.Xna.Framework;
using MonoMod.ModInterop;
using System;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using static On.Celeste.Level;
using static On.Celeste.Player;
using static On.Celeste.SaveData;
using static On.Celeste.Strawberry;

#nullable enable
namespace Celeste.Mod.TheCelesteTracker_Mod
{
    public record class DbSessionContext
    {
        public required GameSession Session { get; set; }
        public required TheCelesteTracker_Mod.Database.SaveData SaveData { get; set; }
        public required Campaign Campaign { get; set; }
        public required Chapter Chapter { get; set; }
    }

    public class SessionRAMData
    {
        public Database.SaveData? CurrentSaveData = null;
        public Campaign? CurrentCampaign = null;
        public Chapter? CurrentChapter = null;
        public GameSession? CurrentSession = null;
        public global::Celeste.Level? CurrentPlayingLevelArea;
        public long SessionStartTicks;
    }

    public class TheCelesteTracker_ModModule : EverestModule
    {
        public static TheCelesteTracker_ModModule Instance { get; private set; } = null!;
        public override Type SettingsType => typeof(TheCelesteTracker_ModModuleSettings);
        public static TheCelesteTracker_ModModuleSettings Settings => (TheCelesteTracker_ModModuleSettings)Instance._Settings;

        public override Type SaveDataType => typeof(TheCelesteTracker_ModModuleSaveData);
        public static TheCelesteTracker_ModModuleSaveData ModSaveData => (TheCelesteTracker_ModModuleSaveData)Instance._SaveData;

        public static SessionRAMData SessionRAM = new();
        public static ISimpleLogger l = new TheCelesteModTrackerLogger();
        public static CelesteTrackerDb DB = null!;
        public static string DbPath = "";

        static TheCelesteTracker_ModModule()
        {
            string sqlitePath = Path.Join(Everest.PathGame, "Mods", "TheCelesteTracker", "bin", "e_sqlite3.dll");
            NativeLibrary.Load(sqlitePath);
#if DEBUG
            DbPath = Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "TheCelesteTracker_MOD_DB_TEST_AUTOGENERATED.db");
#else
            DbPath = Path.Join(Everest.PathGame, "Saves", "TheCelesteTracker_DB.db");
#endif
            DB = new CelesteTrackerDb(DbPath, l);
        }

        public TheCelesteTracker_ModModule()
        {
            Instance = this;
#if DEBUG
            Logger.SetLogLevel(nameof(TheCelesteTracker_ModModule), LogLevel.Verbose);
#else
            Logger.SetLogLevel(nameof(TheCelesteTracker_ModModule), LogLevel.Info);
#endif
        }

        public override void Load()
        {
            typeof(TheCelesteTracker_ModExports).ModInterop();

            // WebSocket Server
            TrackerWebSocketServer.Start();

            // Session and level flow
            On.Celeste.SaveData.StartSession += OnLevelSessionStart;
            On.Celeste.Level.LoadLevel += OnLoadRoomLevel;
            On.Celeste.Level.End += OnLevelSessionEnd;

            // Player only events
            On.Celeste.Player.Jump += OnJump;
            On.Celeste.Player.Die += OnPlayerDeath;
            On.Celeste.Strawberry.OnPlayer += OnStrawberryBeingGrabbedByPlayer;
            On.Celeste.Player.DashBegin += Player_DashBegin;
            On.Celeste.Strawberry.OnCollect += OnStrawberryCollection;

            // Global lifecycle events
            Everest.Events.Celeste.OnShutdown += OnEverestShutdown;
            AppDomain.CurrentDomain.UnhandledException += OnEverestUnhandledExceptionCrash;

            Logger.Log(LogLevel.Info, nameof(TheCelesteTracker_ModModule), "Module Loaded!");

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "ModStarted",
                DatabasePath = DbPath,
                Timestamp = DateTime.UtcNow
            });
        }

        public override void Unload()
        {
            TrackerWebSocketServer.Stop();

            // Session and level flow
            On.Celeste.SaveData.StartSession -= OnLevelSessionStart;
            On.Celeste.Level.LoadLevel -= OnLoadRoomLevel;
            On.Celeste.Level.End -= OnLevelSessionEnd;

            // Player only events
            On.Celeste.Player.Jump -= OnJump;
            On.Celeste.Player.Die -= OnPlayerDeath;
            On.Celeste.Strawberry.OnPlayer -= OnStrawberryBeingGrabbedByPlayer;
            On.Celeste.Player.DashBegin -= Player_DashBegin;
            On.Celeste.Strawberry.OnCollect -= OnStrawberryCollection;

            // Global lifecycle events
            Everest.Events.Celeste.OnShutdown -= OnEverestShutdown;
            AppDomain.CurrentDomain.UnhandledException -= OnEverestUnhandledExceptionCrash;
        }

        // ============= Levels and Global events/hooks =================

        private static async void OnLevelSessionStart(orig_StartSession orig, global::Celeste.SaveData self, global::Celeste.Session session)
        {
            orig(self, session);

            var result = await DB.Session_EnsureInDB(session);
            SessionRAM.CurrentSession = result.Session;
            SessionRAM.CurrentSaveData = result.SaveData;
            SessionRAM.CurrentCampaign = result.Campaign;
            SessionRAM.CurrentChapter = result.Chapter;

            SessionRAM.SessionStartTicks = session.Time;

            l.Log(new { Event = "OnLevelStart" });

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "SessionStarted",
                SessionRAM = SessionRAM
            });
        }

        public static async void OnLoadRoomLevel(orig_LoadLevel orig, global::Celeste.Level self, global::Celeste.Player.IntroTypes playerIntro, bool isFromLoader)
        {
            string lastRoom = SessionRAM.CurrentPlayingLevelArea?.Session.Level ?? "";
            orig(self, playerIntro, isFromLoader);
            SessionRAM.CurrentPlayingLevelArea = self;

            if (lastRoom == self.Session.Level) return;

            l.Log(new { Event = "OnNewRoomLoaded", Room = self.Session.Level });
            if (SessionRAM.CurrentSession is null) return;

            SessionRAM.CurrentSession.AddOrUpdateRoomStat(self);

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "RoomEntered",
                Room = self.Session.Level,
                SessionId = SessionRAM.CurrentSession.id
            });
        }

        private static async void OnLevelSessionEnd(orig_End orig, global::Celeste.Level self)
        {
            orig(self);

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "SessionExited",
                SessionId = SessionRAM.CurrentSession?.id
            });

            if (SessionRAM.CurrentSession is not null)
            {
                int totalJumpsInCurrentSession = SessionRAM.CurrentSession.room_stats.Values.Sum(roomStatistic => roomStatistic.jumps_in_room);
                int totalDashesInCurrentSession = SessionRAM.CurrentSession.room_stats.Values.Sum(roomStatistic => roomStatistic.dashes_in_room);
                int totalDeathsInCurrentSeassion = SessionRAM.CurrentSession.room_stats.Values.Sum(roomStatistic => roomStatistic.deaths_in_room);

                if (totalJumpsInCurrentSession == 0 && totalDashesInCurrentSession == 0 && totalDeathsInCurrentSeassion == 0)
                    return;
            }
            SaveCurrentSessionSync("Current session ended");
        }

        private static void OnEverestShutdown()
        {
            _ = TrackerWebSocketServer.BroadcastEvent(new { Type = "GameClosed", Reason = "Shutdown" });
            SaveCurrentSessionSync("Shutdown");
        }

        private static void OnEverestUnhandledExceptionCrash(object sender, UnhandledExceptionEventArgs e)
        {
            _ = TrackerWebSocketServer.BroadcastEvent(new { Type = "GameClosed", Reason = "Crash" });
            SaveCurrentSessionSync("Crash/UnhandledException");
        }

        private static void SaveCurrentSessionSync(string savingReason)
        {
            if (SessionRAM.CurrentSession is null) return;
            try
            {
                if (SessionRAM.CurrentPlayingLevelArea is not null)
                {
                    long endTicks = SessionRAM.CurrentPlayingLevelArea.Session.Time;
                    long durationTicks = endTicks - SessionRAM.SessionStartTicks;
                    SessionRAM.CurrentSession.duration_ms = durationTicks / 10000;
                }

                DB.GameSession_Insert(SessionRAM.CurrentSession).GetAwaiter().GetResult();
                l.Log(new { Event = "Storing current session in DB [SUCCESS]", TriggerReason = savingReason, SessionId = SessionRAM.CurrentSession.id });

                SessionRAM.CurrentSession = null;
            }
            catch (Exception ex)
            {
                l.Log(new { Event = "Storing current session in db [FAILED]", Reason = savingReason, Error = ex.Message });
            }
        }

        // ============= PLAYER EVENTS ==============

        private static void OnJump(orig_Jump orig, global::Celeste.Player self, bool particles, bool playSfx)
        {
            orig(self, particles, playSfx);
            if (SessionRAM.CurrentSession is null) return;

            SessionRAM.CurrentSession.AddOrUpdateRoomStat(SessionRAM.CurrentPlayingLevelArea, incrementJumpCount: true);

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "Jump",
                TotalJumps = SessionRAM.CurrentSession.room_stats.Values.Sum(r => r.jumps_in_room),
                RoomJumps = SessionRAM.CurrentSession.room_stats.TryGetValue(SessionRAM.CurrentPlayingLevelArea?.Session.Level ?? "", out var s) ? s.jumps_in_room : 0
            });
        }

        private static global::Celeste.PlayerDeadBody OnPlayerDeath(orig_Die orig, global::Celeste.Player self, Vector2 direction, bool evenIfInvincible, bool registerDeathInStats)
        {
            global::Celeste.PlayerDeadBody body = orig(self, direction, evenIfInvincible, registerDeathInStats);

            if (SessionRAM.CurrentSession is not null)
            {
                SessionRAM.CurrentSession.AddOrUpdateRoomStat(SessionRAM.CurrentPlayingLevelArea, incrementDeathCount: true);

                _ = TrackerWebSocketServer.BroadcastEvent(new
                {
                    Type = "Death",
                    TotalDeaths = SessionRAM.CurrentSession.room_stats.Values.Sum(r => r.deaths_in_room),
                    Room = SessionRAM.CurrentPlayingLevelArea?.Session.Level
                });
            }

            return body;
        }

        private static void Player_DashBegin(orig_DashBegin orig, global::Celeste.Player self)
        {
            orig(self);
            if (SessionRAM.CurrentSession is null) return;

            SessionRAM.CurrentSession.AddOrUpdateRoomStat(SessionRAM.CurrentPlayingLevelArea, incrementDashCount: true);

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "Dash",
                TotalDashes = SessionRAM.CurrentSession.room_stats.Values.Sum(r => r.dashes_in_room),
                RoomDashes = SessionRAM.CurrentSession.room_stats.TryGetValue(SessionRAM.CurrentPlayingLevelArea?.Session.Level ?? "", out var s) ? s.dashes_in_room : 0
            });
        }

        private static async void OnStrawberryCollection(orig_OnCollect orig, global::Celeste.Strawberry strawberry)
        {
            bool isAlreadyCollectedBefore = global::Celeste.SaveData.Instance.CheckStrawberry(strawberry.ID);
            orig(strawberry);

            if (SessionRAM.CurrentSession is null) return;

            if (strawberry.Golden)
            {
                SessionRAM.CurrentSession.is_goldenberry_completed = true;
            }

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "StrawberryCollected",
                IsGolden = strawberry.Golden,
                wasPreviouslyCollected = isAlreadyCollectedBefore,
                Room = SessionRAM.CurrentPlayingLevelArea?.Session.Level
            });

            if (isAlreadyCollectedBefore) return;

            SessionRAM.CurrentSession.AddOrUpdateRoomStat(SessionRAM.CurrentPlayingLevelArea, incrementStrawberryAchieved: true);
            await DB.ChapterSide_IncrementBerriesCollected(SessionRAM.CurrentSession.chapter_sid, SessionRAM.CurrentSession.side_id);
        }

        private static void OnStrawberryBeingGrabbedByPlayer(On.Celeste.Strawberry.orig_OnPlayer orig, global::Celeste.Strawberry strawberry, global::Celeste.Player player)
        {
            if (strawberry.collected || strawberry.Follower.Leader != null)
            {
                orig(strawberry, player);
                return;
            }

            orig(strawberry, player);
            if (strawberry.Golden)
            {
                SessionRAM.CurrentSession?.is_goldenberry_attempt = true;
            }

            _ = TrackerWebSocketServer.BroadcastEvent(new
            {
                Type = "StrawberryGrabbed",
                IsGolden = strawberry.Golden,
                Room = strawberry.SceneAs<Level>().Session.Level
            });
        }
    }
}
//private void OnFileSelectSlotCreateButtons(List<OuiFileSelectSlot.Button> buttons, OuiFileSelectSlot slot, EverestModuleSaveData modSaveData, bool fileExists)
//{
//    // 'slot' es el objeto visual de la ranura (ranura 0, 1, 2...)
//    // 'slot.SaveData' contiene la información de vainilla (muertes, tiempo, etc.)
//    Loggy.Log(new
//    {
//        Event = "OnFileSelectSlot",
//        OuiFileSelectSlotListInfoRaw = buttons.Select((button) =>
//        {
//            return new
//            {
//                label = button.Label,
//                scale = button.Scale,
//            };
//        })
//    });

//    if (fileExists && slot.SaveData != null)
//    {
//        int index = slot.buttonIndex;
//        long muertes = slot.SaveData.TotalDeaths;
//        string nombre = slot.SaveData.Name;

//        Logger.Log(LogLevel.Info, "MiTracker", $"Visualizando Slot {index} ({nombre}): {muertes} muertes totales.");
//    }
//}



//private static void OnLevelBegin(On.Celeste.Level.orig_Begin orig, Level self)
//{
//    orig(self);
//    var ev = new
//    {
//        Type = "LevelBegin",
//        AreaSid = self.Session.Area.GetSID(),
//        ChapterName = Dialog.Clean(AreaData.Get(self.Session.Area).Name),
//        RoomName = self.Session.Level,
//        Mode = self.Session.Area.Mode.ToString()
//    };
//    l.Log(ev);
//}



//SessionRAM.CurrentSession.RoomStats.Add(new GameSessionChapterRoomStats
//{
//    RoomName = firstRoom.Name,
//    Deaths = SessionRAM.CurrentRoomDeaths = 0

//});

/// <summary>
/// Not a DATABASE table, just a helpful DTO for internal mod use.
/// </summary>
//public record class LocalChapterRoomInfo
//{
//    public required int Deaths;
//    public required int Dashes;
//    public required int StrawberriesAchieved;
//    public required int HeartsAchieved;
//}

///// <summary>
///// When going to next room only in same chapter (Moving across rooms)
///// </summary>
//private static void OnNextRoom(orig_NextLevel orig, global::Celeste.Level self, Vector2 at, Vector2 dir)
//{
//    orig(self, at, dir);
//    l.Log(new { Event = "Level_NextLevel", RoomInfo = new { CurrentDeaths = self.Session.Deaths } });//Full total count of datasave for some reason
//}


//ame chapter(Moving across rooms)
///// </summary>
//private static void OnNextRoom(orig_NextLevel orig, global::Celeste.Level self, Vector2 at, Vector2 dir)
//{
//    orig(self, at, dir);
//    l.Log(new { Event = "Level_NextLevel", RoomInfo = new { CurrentDeaths = self.Session.Deaths } });//Full total count of datasave for some reason
//}


